default:
  image: debian:bookworm-slim

stages:
  - build

build rock-5b:
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    GIT_SUBMODULE_STRATEGY: normal
    RKBIN_REPO_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/hardware-enablement/rockchip-3588/rkbin.git
  before_script:
    - apt update
    - apt install -y bc build-essential
                        crossbuild-essential-arm64
                        device-tree-compiler
                        git
                        python3
                        bison
                        flex
                        python3-setuptools
                        swig
                        python3-dev
                        libssl-dev
                        python3-pyelftools

  script:
    # download rkbin
    - git clone --depth 1 -b master ${RKBIN_REPO_URL} $CI_PROJECT_DIR/../rkbin

    # prepare PATH
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export ARCH=arm64
    - export BL31=../rkbin/bin/rk35/rk3588_bl31_v1.27.elf
    - export ROCKCHIP_TPL=../rkbin/bin/rk35/rk3588_ddr_lp4_2112MHz_lp5_2736MHz_v1.08.bin

    # build
    - cd $CI_PROJECT_DIR
    - make rock5b-rk3588_defconfig
    - make -j$(nproc)
    - ../rkbin/tools/boot_merger rock5b-rk3588.ini

    # build proprietary usb loader
    # the directory-dance here is because boot_merger shipped in rkbin
    # doesn't seem to support the "--prepath" option which is available in
    # downstream U-Boot.
    - cd ../rkbin && ./tools/boot_merger RKBOOT/RK3588MINIALL.ini && mv *spl_loader*.bin ../u-boot/
  artifacts:
    paths:
      - u-boot.itb
      - idbloader.img
      - u-boot-rockchip.bin
      - u-boot-rockchip-spi.bin
      - rock5b-rk3588.bin
      - rk3588_spl_loader_*.bin
